# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20170514_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='city',
            new_name='location',
        ),
        migrations.AlterIndexTogether(
            name='facility',
            index_together=set([('location', 'updated_date')]),
        ),
    ]
