# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170522_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='yelp_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
