# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20170522_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image_url',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='facility',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
